In [3]:
import numpy as np

In [9]:
x = np.array([1., 1., 1.], dtype=np.float32)
x

array([1., 1., 1.], dtype=float32)

In [10]:
np.sin(x)

array([0.841471, 0.841471, 0.841471], dtype=float32)

In [11]:
x.shape

(3,)

In [21]:
y=np.ones((3,3,3))
y

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
a = np.linspace(1,10,10).reshape(2,5)
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [25]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [26]:
rg = np.random.default_rng(2)
rg

Generator(PCG64) at 0x1AC750B2D60

In [28]:
b=rg.random((2,2))
b

array([[0.60010053, 0.72856053],
       [0.18790107, 0.05514663]])

In [30]:
c = 5* np.ones((2,2))
c*b

array([[3.00050263, 3.64280263],
       [0.93950537, 0.27573314]])